# Generated by Django 6.0.3 on 2026-03-29 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_quiz_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='wordset',
            new_name='word_set',
        ),
        migrations.RenameField(
            model_name='wordset',
            old_name='is_public',
            new_name='public',
        ),
        migrations.AddField(
            model_name='quiz',
            name='name',
            field=models.CharField(default='Quiz', max_length=100),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='word_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='api.wordset'),
        ),
    ]
