# Generated by Codex on 2026-06-08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_userwordprogress"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserQuizResult",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("correct_count", models.IntegerField(default=0)),
                ("total_questions", models.IntegerField(default=0)),
                ("score_percentage", models.FloatField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("quiz", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="results", to="api.quiz")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="quiz_results", to=settings.AUTH_USER_MODEL)),
                ("word_set", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="quiz_results", to="api.wordset")),
            ],
        ),
    ]
