# Generated by Codex on 2026-06-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_userquizresult"),
    ]

    operations = [
        migrations.AddField(
            model_name="userwordprogress",
            name="is_mastered",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userwordprogress",
            name="needs_review",
            field=models.BooleanField(default=False),
        ),
    ]
